# 1단계: 빌드 단계
FROM node:20-alpine AS builder

WORKDIR /app

# ARG로 환경변수 받기
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_AI_URL
ARG NEXT_PUBLIC_DEV_MODE
ARG NEXT_PUBLIC_LOG_LEVEL
ARG NEXT_PUBLIC_TOKEN_KEY
ARG NEXT_PUBLIC_REFRESH_TOKEN_KEY
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_VERSION

# 빌드 시점에 환경변수로 전달
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_AI_URL=$NEXT_PUBLIC_AI_URL
ENV NEXT_PUBLIC_DEV_MODE=$NEXT_PUBLIC_DEV_MODE
ENV NEXT_PUBLIC_LOG_LEVEL=$NEXT_PUBLIC_LOG_LEVEL
ENV NEXT_PUBLIC_TOKEN_KEY=$NEXT_PUBLIC_TOKEN_KEY
ENV NEXT_PUBLIC_REFRESH_TOKEN_KEY=$NEXT_PUBLIC_REFRESH_TOKEN_KEY
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION

# 의존성 설치 (npm ci는 더 빠르고 메모리 효율적)
COPY package*.json ./
RUN npm ci --prefer-offline --no-audit

# 소스 코드 복사
COPY . .

# Node.js 힙 메모리 증가 (4GB) - Next.js 15 빌드를 위해 필수
ENV NODE_OPTIONS="--max-old-space-size=4096"

# 환경변수 전달 확인 (디버그용)
RUN echo "🔍 DEV_MODE=$NEXT_PUBLIC_DEV_MODE"

# 환경변수가 설정된 상태에서 빌드
RUN npm run build

# 2단계: 실행 단계
FROM node:20-alpine

WORKDIR /app

# 빌드된 앱 복사
COPY --from=builder /app ./

# NEXT_PUBLIC_ 환경변수는 빌드 타임에 이미 번들에 포함되므로 런타임 설정 불필요

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "start"]